/*
MIT License

Copyright (c) 2026 TMagnusN

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

#include "Attack.h"

#include <array>
#include <bit>
#include <vector>

#if !defined(MAGNUS_DISABLE_PEXT) \
 && (defined(__x86_64__) || defined(_M_X64) || defined(__i386) || defined(_M_IX86)) \
 && (defined(__GNUC__) || defined(__clang__))
    #include <immintrin.h>
    #define MAGNUS_CAN_COMPILE_PEXT 1
    #define MAGNUS_TARGET_BMI2 __attribute__((target("bmi2")))
#else
    #define MAGNUS_CAN_COMPILE_PEXT 0
    #define MAGNUS_TARGET_BMI2
#endif

/*
This file implements the slider attack backends. It can fall back to classical
ray scans, use dense lookup tables, or exploit BMI2/PEXT when available.
*/

/* ===== 繁體中文註釋 =====
 * 本檔案是 MagnusChessX Thinking 西洋棋引擎的一部分。
 * 實作詳情請參閱對應的 .h 標頭檔案。
 */

namespace magnus {

namespace {

using SliderAttackFn =
    AttackBitboard (*)(const memory::Memory&, int, AttackBitboard) noexcept;

struct AttackBackendVTable {
    SliderAttackFn bishop;
    SliderAttackFn rook;
    AttackBackendKind kind;
    const char* name;
    bool uses_slider_tables;
};

std::array<SliderAttackEntry, 64> g_bishop_entries{};
std::array<SliderAttackEntry, 64> g_rook_entries{};
std::vector<AttackBitboard> g_bishop_table;
std::vector<AttackBitboard> g_rook_table;
std::vector<AttackBitboard> g_bishop_magic_table;
std::vector<AttackBitboard> g_rook_magic_table;
bool g_slider_tables_ready = false;
bool g_magic_tables_initialized = false;
bool g_magic_tables_valid = false;

// Generated by a deterministic sparse-random search. Keeping the discovered
// multipliers fixed makes startup deterministic and avoids runtime searches.
constexpr std::array<AttackBitboard, 64> BISHOP_MAGICS {{
    0x0008220808002284ULL,
    0x0004818801010100ULL,
    0x4010010861020010ULL,
    0x0091041080010000ULL,
    0x0901104080008808ULL,
    0x020208020a004020ULL,
    0x8000410808400000ULL,
    0x1102018401093000ULL,
    0x0008409004810040ULL,
    0x42004808c8088020ULL,
    0x0200462802108000ULL,
    0x1429110414800002ULL,
    0x00806a1210042020ULL,
    0x0801011002111010ULL,
    0x48002a0804048406ULL,
    0x0104c23088041000ULL,
    0x0504840aa0082200ULL,
    0x0108181218014411ULL,
    0x0001100800440080ULL,
    0x2020840812004020ULL,
    0x0001022820080040ULL,
    0x020e010022100200ULL,
    0x0454040202322254ULL,
    0x040a511023041001ULL,
    0x0120100049024800ULL,
    0x8a01100008104108ULL,
    0x2290444010110200ULL,
    0x2902080004004108ULL,
    0x4002002002008044ULL,
    0x104e041006004214ULL,
    0x3082320100480201ULL,
    0x000c104c40221200ULL,
    0x8202382402222008ULL,
    0x2001180230081080ULL,
    0x0004004408880030ULL,
    0x10841c0401880210ULL,
    0x0000408020420200ULL,
    0x0010100c41008044ULL,
    0x0024014200044802ULL,
    0x8400811440110400ULL,
    0xd002021040040480ULL,
    0x608a220220808200ULL,
    0x4802020224000a00ULL,
    0x1008204200800801ULL,
    0x880020020c000081ULL,
    0x001002080240080cULL,
    0x4020010111000200ULL,
    0x005282040b080020ULL,
    0x8804042402080401ULL,
    0x001020880808084cULL,
    0x8000020100881200ULL,
    0x0818000220882803ULL,
    0x0100001202020000ULL,
    0x00a220a022008844ULL,
    0x2004101002408004ULL,
    0x00128808150d4002ULL,
    0x4082808401014003ULL,
    0x0404024262101004ULL,
    0x1040000100809000ULL,
    0x4008008030840400ULL,
    0x0140400091020200ULL,
    0x0100102005011201ULL,
    0x4840040842080201ULL,
    0x00101400b0860200ULL
}};

constexpr std::array<AttackBitboard, 64> ROOK_MAGICS {{
    0x0080021620804001ULL,
    0x0040001000200041ULL,
    0x0200102200088040ULL,
    0x4080040800821000ULL,
    0x2200020004200810ULL,
    0x4b00020c000d0008ULL,
    0x01000c4183000600ULL,
    0x2080010000402c80ULL,
    0x8002800826864000ULL,
    0x0410802000884000ULL,
    0x0c01004010200100ULL,
    0x020300100100203cULL,
    0x0450800801040080ULL,
    0x4010800200040080ULL,
    0x8804000208048110ULL,
    0x0c40800080004100ULL,
    0xa2018880024004a0ULL,
    0x0080848020004004ULL,
    0x1010410010200101ULL,
    0x2010008008008010ULL,
    0x0a08010004110008ULL,
    0x0802080104209040ULL,
    0x0080040090010802ULL,
    0x0280020000841069ULL,
    0x080c400080248000ULL,
    0x2048850100224008ULL,
    0x00200800c0300040ULL,
    0x11400d0100201000ULL,
    0x0041001100080204ULL,
    0x4802000200040810ULL,
    0x0100080c00103601ULL,
    0x0020084200043085ULL,
    0x0100804000800022ULL,
    0x0460401000402002ULL,
    0x8309002001001044ULL,
    0x0000800800801000ULL,
    0x0000800800800400ULL,
    0xb542040080800200ULL,
    0x1041000401000200ULL,
    0x000318b04a000401ULL,
    0x0280082000484000ULL,
    0x0080400081010030ULL,
    0x0010002000108080ULL,
    0x012010002101000aULL,
    0x0801000408010012ULL,
    0x0004008002008004ULL,
    0x0ad1005200110014ULL,
    0x4000004110820004ULL,
    0x9400400080003080ULL,
    0x0000802200490200ULL,
    0x1521100080200280ULL,
    0x9021000824100100ULL,
    0x0081080080840280ULL,
    0x0002000904100200ULL,
    0x0130024801302400ULL,
    0x0102008100442200ULL,
    0x0080984063800101ULL,
    0x0016810201412812ULL,
    0x40200101603008c1ULL,
    0x2851100004082101ULL,
    0x1049001002880005ULL,
    0x0081000804000201ULL,
    0x100020901208410cULL,
    0x0101064400813102ULL
}};


// March a ray square by square until the board edge or the first blocker.
inline AttackBitboard scan_ray(
    int sq,
    int df,
    int dr,
    AttackBitboard occupied
) noexcept {
    AttackBitboard attacks = 0ULL;

    int f = attack_file_of(sq) + df;
    int r = attack_rank_of(sq) + dr;

    while (f >= 0 && f < 8 && r >= 0 && r < 8) {
        const int to = r * 8 + f;
        const AttackBitboard to_bb = attack_bb_of(to);

        attacks |= to_bb;
        if (occupied & to_bb)
            break;

        f += df;
        r += dr;
    }

    return attacks;
}

inline AttackBitboard bishop_attacks_classical_impl(
    int sq,
    AttackBitboard occupied
) noexcept {
    return scan_ray(sq,  1,  1, occupied)
         | scan_ray(sq,  1, -1, occupied)
         | scan_ray(sq, -1,  1, occupied)
         | scan_ray(sq, -1, -1, occupied);
}

inline AttackBitboard rook_attacks_classical_impl(
    int sq,
    AttackBitboard occupied
) noexcept {
    return scan_ray(sq,  1,  0, occupied)
         | scan_ray(sq, -1,  0, occupied)
         | scan_ray(sq,  0,  1, occupied)
         | scan_ray(sq,  0, -1, occupied);
}

AttackBitboard bishop_attacks_classical(
    const memory::Memory& mem,
    int sq,
    AttackBitboard occupied
) noexcept {
    (void)mem;
    return bishop_attacks_classical_impl(sq, occupied);
}

AttackBitboard rook_attacks_classical(
    const memory::Memory& mem,
    int sq,
    AttackBitboard occupied
) noexcept {
    (void)mem;
    return rook_attacks_classical_impl(sq, occupied);
}

inline AttackBitboard bishop_relevant_mask(int sq) noexcept {
    AttackBitboard mask = 0ULL;
    const int file = attack_file_of(sq);
    const int rank = attack_rank_of(sq);

    for (int f = file + 1, r = rank + 1; f <= 6 && r <= 6; ++f, ++r)
        mask |= attack_bb_of(r * 8 + f);
    for (int f = file + 1, r = rank - 1; f <= 6 && r >= 1; ++f, --r)
        mask |= attack_bb_of(r * 8 + f);
    for (int f = file - 1, r = rank + 1; f >= 1 && r <= 6; --f, ++r)
        mask |= attack_bb_of(r * 8 + f);
    for (int f = file - 1, r = rank - 1; f >= 1 && r >= 1; --f, --r)
        mask |= attack_bb_of(r * 8 + f);

    return mask;
}

inline AttackBitboard rook_relevant_mask(int sq) noexcept {
    AttackBitboard mask = 0ULL;
    const int file = attack_file_of(sq);
    const int rank = attack_rank_of(sq);

    for (int f = file + 1; f <= 6; ++f)
        mask |= attack_bb_of(rank * 8 + f);
    for (int f = file - 1; f >= 1; --f)
        mask |= attack_bb_of(rank * 8 + f);
    for (int r = rank + 1; r <= 6; ++r)
        mask |= attack_bb_of(r * 8 + file);
    for (int r = rank - 1; r >= 1; --r)
        mask |= attack_bb_of(r * 8 + file);

    return mask;
}

inline AttackBitboard set_occupancy_from_index(
    std::uint32_t index,
    AttackBitboard mask
) noexcept {
    AttackBitboard occ = 0ULL;

    while (mask) {
        const AttackBitboard bit = mask & (~mask + 1ULL);
        mask ^= bit;
        if (index & 1U)
            occ |= bit;
        index >>= 1;
    }

    return occ;
}

inline std::uint32_t dense_index_from_occupied(
    AttackBitboard occupied,
    AttackBitboard mask
) noexcept {
    occupied &= mask;

    std::uint32_t index = 0;
    std::uint32_t bit_index = 0;

    while (mask) {
        const AttackBitboard bit = mask & (~mask + 1ULL);
        mask ^= bit;
        if (occupied & bit)
            index |= (1U << bit_index);
        ++bit_index;
    }

    return index;
}

inline std::uint32_t magic_index_from_occupied(
    AttackBitboard occupied,
    const SliderAttackEntry& entry
) noexcept {
    return static_cast<std::uint32_t>(
        ((occupied & entry.mask) * entry.magic) >> entry.shift
    );
}

#if MAGNUS_CAN_COMPILE_PEXT
MAGNUS_TARGET_BMI2 bool query_cpu_bmi2_support() noexcept {
    __builtin_cpu_init();
    return __builtin_cpu_supports("bmi2");
}

MAGNUS_TARGET_BMI2 std::uint32_t pext_index_from_occupied(
    AttackBitboard occupied,
    AttackBitboard mask
) noexcept {
    return static_cast<std::uint32_t>(_pext_u64(occupied, mask));
}

MAGNUS_TARGET_BMI2 AttackBitboard bishop_attacks_pext(
    const memory::Memory& mem,
    int sq,
    AttackBitboard occupied
) noexcept {
    (void)mem;
    const SliderAttackEntry& e = g_bishop_entries[sq];
    return g_bishop_table[e.offset + pext_index_from_occupied(occupied, e.mask)];
}

MAGNUS_TARGET_BMI2 AttackBitboard rook_attacks_pext(
    const memory::Memory& mem,
    int sq,
    AttackBitboard occupied
) noexcept {
    (void)mem;
    const SliderAttackEntry& e = g_rook_entries[sq];
    return g_rook_table[e.offset + pext_index_from_occupied(occupied, e.mask)];
}
#else
bool query_cpu_bmi2_support() noexcept {
    return false;
}
#endif

/*
 * 攻擊生成實作
 * init_slider_tables() — 構建稠密索引滑子攻擊表（主教+城堡）
 * set_occupancy_from_index() — 從索引還原佔位位元棋盤
 * dense_index_from_occupied() — 從佔位計算稠密索引（PEXT 或乘法雜湊）
 * attack_auto_select_backend() — 自動選擇最快可用的攻擊後端
 */
void init_slider_table(
    std::array<SliderAttackEntry, 64>& entries,
    std::vector<AttackBitboard>& table,
    AttackBitboard (*mask_fn)(int) noexcept,
    AttackBitboard (*attack_fn)(int, AttackBitboard) noexcept
) {
    // Build a dense occupancy-indexed lookup table for each source square.
    entries.fill({});

    std::size_t total_size = 0;
    for (int sq = 0; sq < 64; ++sq) {
        const AttackBitboard mask = mask_fn(sq);
        const auto relevant_bits = static_cast<std::uint8_t>(std::popcount(mask));
        entries[sq].mask = mask;
        entries[sq].offset = static_cast<std::uint32_t>(total_size);
        entries[sq].relevant_bits = relevant_bits;
        entries[sq].shift = static_cast<std::uint8_t>(64 - relevant_bits);
        total_size += (std::size_t{1} << relevant_bits);
    }

    table.assign(total_size, 0ULL);

    for (int sq = 0; sq < 64; ++sq) {
        const SliderAttackEntry& e = entries[sq];
        const std::uint32_t count = (1U << e.relevant_bits);

        for (std::uint32_t idx = 0; idx < count; ++idx) {
            const AttackBitboard occ = set_occupancy_from_index(idx, e.mask);
            table[e.offset + idx] = attack_fn(sq, occ);
        }
    }
}

void init_slider_tables() {
    if (g_slider_tables_ready)
        return;

    init_slider_table(g_bishop_entries, g_bishop_table,
                      &bishop_relevant_mask,
                      &bishop_attacks_classical_impl);
    init_slider_table(g_rook_entries, g_rook_table,
                      &rook_relevant_mask,
                      &rook_attacks_classical_impl);

    g_slider_tables_ready = true;
}

bool init_magic_table(
    std::array<SliderAttackEntry, 64>& entries,
    const std::vector<AttackBitboard>& dense_table,
    std::vector<AttackBitboard>& magic_table,
    const std::array<AttackBitboard, 64>& magics
) {
    magic_table.assign(dense_table.size(), 0ULL);

    for (int sq = 0; sq < 64; ++sq) {
        SliderAttackEntry& entry = entries[sq];
        entry.magic = magics[sq];

        const std::uint32_t count = 1U << entry.relevant_bits;
        std::vector<bool> used(count, false);

        for (std::uint32_t dense_index = 0; dense_index < count; ++dense_index) {
            const AttackBitboard occupied =
                set_occupancy_from_index(dense_index, entry.mask);
            const std::uint32_t magic_index =
                magic_index_from_occupied(occupied, entry);
            const AttackBitboard attacks =
                dense_table[entry.offset + dense_index];
            AttackBitboard& slot = magic_table[entry.offset + magic_index];

            if (used[magic_index] && slot != attacks)
                return false;

            used[magic_index] = true;
            slot = attacks;
        }
    }

    return true;
}

void init_magic_tables() {
    if (g_magic_tables_initialized)
        return;

    init_slider_tables();
    g_magic_tables_valid =
        init_magic_table(
            g_bishop_entries,
            g_bishop_table,
            g_bishop_magic_table,
            BISHOP_MAGICS
        )
        && init_magic_table(
            g_rook_entries,
            g_rook_table,
            g_rook_magic_table,
            ROOK_MAGICS
        );
    g_magic_tables_initialized = true;
}

AttackBitboard bishop_attacks_table(
    const memory::Memory& mem,
    int sq,
    AttackBitboard occupied
) noexcept {
    (void)mem;
    const SliderAttackEntry& e = g_bishop_entries[sq];
    return g_bishop_table[e.offset + dense_index_from_occupied(occupied, e.mask)];
}

AttackBitboard rook_attacks_table(
    const memory::Memory& mem,
    int sq,
    AttackBitboard occupied
) noexcept {
    (void)mem;
    const SliderAttackEntry& e = g_rook_entries[sq];
    return g_rook_table[e.offset + dense_index_from_occupied(occupied, e.mask)];
}

AttackBitboard bishop_attacks_magic(
    const memory::Memory& mem,
    int sq,
    AttackBitboard occupied
) noexcept {
    (void)mem;
    const SliderAttackEntry& e = g_bishop_entries[sq];
    return g_bishop_magic_table[
        e.offset + magic_index_from_occupied(occupied, e)
    ];
}

AttackBitboard rook_attacks_magic(
    const memory::Memory& mem,
    int sq,
    AttackBitboard occupied
) noexcept {
    (void)mem;
    const SliderAttackEntry& e = g_rook_entries[sq];
    return g_rook_magic_table[
        e.offset + magic_index_from_occupied(occupied, e)
    ];
}

bool pext_supported_runtime() noexcept {
    static const bool supported = query_cpu_bmi2_support();
    return supported;
}

AttackBackendVTable g_attack_backend {
    &bishop_attacks_classical,
    &rook_attacks_classical,
    AttackBackendKind::CLASSICAL,
    "classical",
    false
};

} // namespace

void attack_init_backend(memory::Memory& mem) noexcept {
    (void)mem;
    // Initialize shared tables once, then pick the fastest available backend.
    init_slider_tables();
    attack_auto_select_backend();
}

void attack_set_backend(AttackBackendKind kind) noexcept {
    switch (kind) {
        case AttackBackendKind::PEXT:
            init_slider_tables();
#if MAGNUS_CAN_COMPILE_PEXT
            if (pext_supported_runtime()) {
                g_attack_backend.bishop = &bishop_attacks_pext;
                g_attack_backend.rook   = &rook_attacks_pext;
                g_attack_backend.kind   = AttackBackendKind::PEXT;
                g_attack_backend.name   = "pext";
                g_attack_backend.uses_slider_tables = true;
                break;
            }
#endif
            [[fallthrough]];

        case AttackBackendKind::MAGIC:
            init_magic_tables();
            if (g_magic_tables_valid) {
                g_attack_backend.bishop = &bishop_attacks_magic;
                g_attack_backend.rook   = &rook_attacks_magic;
                g_attack_backend.kind   = AttackBackendKind::MAGIC;
                g_attack_backend.name   = "magic";
                g_attack_backend.uses_slider_tables = true;
                break;
            }
            [[fallthrough]];

        case AttackBackendKind::TABLE:
            init_slider_tables();
            g_attack_backend.bishop = &bishop_attacks_table;
            g_attack_backend.rook   = &rook_attacks_table;
            g_attack_backend.kind   = AttackBackendKind::TABLE;
            g_attack_backend.name   = "table";
            g_attack_backend.uses_slider_tables = true;
            break;

        case AttackBackendKind::CLASSICAL:
        default:
            g_attack_backend.bishop = &bishop_attacks_classical;
            g_attack_backend.rook   = &rook_attacks_classical;
            g_attack_backend.kind   = AttackBackendKind::CLASSICAL;
            g_attack_backend.name   = "classical";
            g_attack_backend.uses_slider_tables = false;
            break;
    }
}

void attack_auto_select_backend() noexcept {
    attack_set_backend(AttackBackendKind::PEXT);
}

bool attack_select_backend(std::string_view name) noexcept {
    if (name == "auto") {
        attack_auto_select_backend();
        return true;
    }
    if (name == "pext") {
        attack_set_backend(AttackBackendKind::PEXT);
        return true;
    }
    if (name == "magic") {
        attack_set_backend(AttackBackendKind::MAGIC);
        return true;
    }
    if (name == "table") {
        attack_set_backend(AttackBackendKind::TABLE);
        return true;
    }
    if (name == "classical") {
        attack_set_backend(AttackBackendKind::CLASSICAL);
        return true;
    }
    return false;
}

AttackBackendKind attack_backend_kind() noexcept {
    return g_attack_backend.kind;
}

const char* attack_backend_name() noexcept {
    return g_attack_backend.name;
}

bool attack_backend_uses_slider_tables() noexcept {
    return g_attack_backend.uses_slider_tables;
}

bool attack_backend_pext_supported() noexcept {
    return pext_supported_runtime();
}

const SliderAttackEntry& bishop_slider_entry(int sq) noexcept {
    return g_bishop_entries[sq];
}

const SliderAttackEntry& rook_slider_entry(int sq) noexcept {
    return g_rook_entries[sq];
}

std::size_t bishop_slider_table_size() noexcept {
    return g_bishop_table.size();
}

std::size_t rook_slider_table_size() noexcept {
    return g_rook_table.size();
}

const AttackBitboard* bishop_slider_table_data() noexcept {
    return g_bishop_table.data();
}

const AttackBitboard* rook_slider_table_data() noexcept {
    return g_rook_table.data();
}

AttackBitboard bishop_attacks(
    const memory::Memory& mem,
    int sq,
    AttackBitboard occupied
) noexcept {
    return g_attack_backend.bishop(mem, sq, occupied);
}

AttackBitboard rook_attacks(
    const memory::Memory& mem,
    int sq,
    AttackBitboard occupied
) noexcept {
    return g_attack_backend.rook(mem, sq, occupied);
}

AttackBitboard bishop_attacks_fast(
    const memory::Memory& mem,
    int sq,
    AttackBitboard occupied
) noexcept {
    if (g_attack_backend.kind == AttackBackendKind::PEXT) {
#if MAGNUS_CAN_COMPILE_PEXT
        return bishop_attacks_pext(mem, sq, occupied);
#else
        return bishop_attacks_magic(mem, sq, occupied);
#endif
    }

    if (g_attack_backend.kind == AttackBackendKind::MAGIC)
        return bishop_attacks_magic(mem, sq, occupied);

    if (g_attack_backend.kind == AttackBackendKind::TABLE)
        return bishop_attacks_table(mem, sq, occupied);

    return bishop_attacks_classical(mem, sq, occupied);
}

AttackBitboard rook_attacks_fast(
    const memory::Memory& mem,
    int sq,
    AttackBitboard occupied
) noexcept {
    if (g_attack_backend.kind == AttackBackendKind::PEXT) {
#if MAGNUS_CAN_COMPILE_PEXT
        return rook_attacks_pext(mem, sq, occupied);
#else
        return rook_attacks_magic(mem, sq, occupied);
#endif
    }

    if (g_attack_backend.kind == AttackBackendKind::MAGIC)
        return rook_attacks_magic(mem, sq, occupied);

    if (g_attack_backend.kind == AttackBackendKind::TABLE)
        return rook_attacks_table(mem, sq, occupied);

    return rook_attacks_classical(mem, sq, occupied);
}

namespace {

AttackBitboard scan_empty_ray(
    int sq,
    int rank_delta,
    int file_delta
) noexcept {
    AttackBitboard attacks = 0ULL;
    int rank = attack_rank_of(sq) + rank_delta;
    int file = attack_file_of(sq) + file_delta;

    while (rank >= 0 && rank < ATTACK_RANK_NB &&
           file >= 0 && file < ATTACK_FILE_NB) {
        attacks |= attack_bb_of(rank * ATTACK_FILE_NB + file);
        rank += rank_delta;
        file += file_delta;
    }

    return attacks;
}

} // namespace

AttackBitboard bishop_rays(int sq) noexcept {
    return scan_empty_ray(sq, 1, 1)
         | scan_empty_ray(sq, 1, -1)
         | scan_empty_ray(sq, -1, 1)
         | scan_empty_ray(sq, -1, -1);
}

AttackBitboard rook_rays(int sq) noexcept {
    return scan_empty_ray(sq, 1, 0)
         | scan_empty_ray(sq, -1, 0)
         | scan_empty_ray(sq, 0, 1)
         | scan_empty_ray(sq, 0, -1);
}

AttackBitboard bishop_xray_attacks(
    const memory::Memory& mem,
    int sq,
    AttackBitboard occupied,
    AttackBitboard blockers
) noexcept {
    const AttackBitboard attacks = bishop_attacks(mem, sq, occupied);
    const AttackBitboard screened = attacks & blockers;

    if (!screened)
        return attacks;

    return attacks ^ bishop_attacks(mem, sq, occupied ^ screened);
}

AttackBitboard rook_xray_attacks(
    const memory::Memory& mem,
    int sq,
    AttackBitboard occupied,
    AttackBitboard blockers
) noexcept {
    const AttackBitboard attacks = rook_attacks(mem, sq, occupied);
    const AttackBitboard screened = attacks & blockers;

    if (!screened)
        return attacks;

    return attacks ^ rook_attacks(mem, sq, occupied ^ screened);
}

bool same_file(int a, int b) noexcept {
    return attack_file_of(a) == attack_file_of(b);
}

bool same_rank(int a, int b) noexcept {
    return attack_rank_of(a) == attack_rank_of(b);
}

bool same_diagonal(int a, int b) noexcept {
    return abs_i(attack_file_of(a) - attack_file_of(b)) ==
           abs_i(attack_rank_of(a) - attack_rank_of(b));
}

bool aligned(int a, int b) noexcept {
    return same_file(a, b) || same_rank(a, b) || same_diagonal(a, b);
}

} // namespace magnus
